version: "3.9"

services:
  ground:
    build:
      context: ../../..
      dockerfile: dockers/ground/jetson/Dockerfile
    image: operator_station-ground # see under docker images
    container_name: operator_station-ground-container
    network_mode: host
    # Match host user and group for PulseAudio permissions
    user: "${UID}:${GID}"

    # Access to audio devices
    devices:
      - /dev/snd

    # Environment variable tells apps where the PulseAudio socket is
    environment:
      - PULSE_SERVER=unix:/run/user/1000/pulse/native
      - PYTHONPATH=/app
      - HOME=/home/appuser

    # Mount the PulseAudio socket and needed folders
    volumes:
      - ${HOME}/.config/pulse/cookie:/home/appuser/.config/pulse/cookie:ro
      - /mnt/nvme/repo/Agenteam_V2:/app
      - /run/user/1000/pulse:/run/user/1000/pulse        # PulseAudio socket
      - /mnt/nvme:/mnt/nvme                              # Audio output files
      - /mnt/nvme/outputs:/mnt/nvme/outputs
      # Mount custom OpenWakeWord models
      - /mnt/nvme/repo/Agenteam_V2/project_code/audio/wakeword_models/wakeword_models:/usr/local/lib/python3.10/dist-packages/openwakeword/resources/models
      - ${HOME}/.config/pulse/cookie:/root/.config/pulse/cookie
      - /tmp/pulse:/tmp/pulse


    group_add:
      - audio

    extra_hosts:
      - "host.docker.internal:host-gateway"

    working_dir: /app/project_code

    command: python3 ground/mainGround.py


    # Optional: restart automatically if it crashes
    #restart: unless-stopped # restart: always, unless-stopped