services:
  vllm-gpt-oss-20b:
    container_name: vllm-gpt-oss-20b
    build:
      context: ..
      dockerfile: Dockerfile

    ports:
      - "8090:8090"

    environment:
      - NVIDIA_VISIBLE_DEVICES=all

    runtime: nvidia

    command:
      - bash
      - -c
      - |
          sleep 1
          python3 -m vllm.entrypoints.openai.api_server \
            --model /models/openai-gpt-oss-20b \
            --gpu-memory-utilization 0.90 \
            --max-model-len 32768 \
            --port 8090

    volumes:
      - /mnt/nvme/repo/Agenteam_V2/dockers/llm:/models

    shm_size: "16gb"
    restart: always