services:
  vllm-phi3-mini:
    container_name: vllm-phi3-mini
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8095:8095"

    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - HF_HUB_OFFLINE=1
      - TRANSFORMERS_OFFLINE=1

    runtime: nvidia

    command:
      - bash
      - -c
      - |
        sleep 1
        python3 -m vllm.entrypoints.openai.api_server \
          --model /models/Phi-3-mini-4k-instruct \
          --gpu-memory-utilization 0.20 \
          --max-model-len 3600 \
          --port 8095

    volumes:
      - /mnt/nvme/repo/Agenteam_V2/dockers/llm:/models
      - ${HOME}/.cache/huggingface:/root/.cache/huggingface

    shm_size: "16gb"
    restart: always
